spring:
  data:
    mongodb:
      port: 8099
      database: hw_db
  datasource:
    username: postgres
    password: qwerty
    url: jdbc:postgresql://localhost:5432/postgres
  # url: jdbc:h2:mem:testdb
  sql:
    init:
      mode: never
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master-test.yaml
  jpa:
    hibernate:
      ddl-auto: none
    generate-ddl: false
  shell:
    interactive:
      enabled: true
    noninteractive:
      enabled: false
    command:
      version:
        enabled: false

de:
  flapdoodle:
    mongodb:
      embedded:
        version: 4.0.2

mongock:
  runner-type: InitializingBean
  change-logs-scan-package: ru.otus.hw.mongo.mongock.changelog
  mongo-db:
    write-concern:
      journal: false
    read-concern: local