spring:
  datasource:
    url: jdbc:h2:mem:maindb
  sql:
    init:
      mode: never
  liquibase:
    enabled: true
  jpa:
    generate-ddl: false
    open-in-view: false
    hibernate:
      ddl-auto: none
  mvc:
    hiddenmethod:
      filter:
        enabled: true
security:
  token-sign-key: AnyKey
  token-valid-second: 1000